print(int("100"))
print(float("25.5"))
print(str(500))
print(bool(1))
print(list((1, 2, 3)))
print(tuple([1, 2, 3]))
print(set([1, 1, 2, 3]))
print(dict([("name", "Ravi"), ("score", 90)]))
print(complex(3, 4))
print(bytes("ABC", "utf-8"))
print(bytearray("ABC", "utf-8"))
