"""Common string methods with examples."""

text = "  Python Programming for Data Analytics  "

print("strip:", text.strip())
print("lower:", text.lower())
print("upper:", text.upper())
print("title:", text.title())
print("capitalize:", text.capitalize())
print("casefold:", text.casefold())
print("swapcase:", text.swapcase())
print("replace:", text.replace("Data Analytics", "AI"))
print("split:", text.split())
print("partition:", text.partition("Programming"))
print("find:", text.find("Python"))
print("index:", text.index("Programming"))
print("count:", text.count("a"))
print("startswith:", text.strip().startswith("Python"))
print("endswith:", text.strip().endswith("Analytics"))
print("isalpha:", "Python".isalpha())
print("isdigit:", "2026".isdigit())
print("isalnum:", "Python311".isalnum())
print("isspace:", "   ".isspace())
print("join:", "-".join(["2026", "07", "27"]))
print("center:", "Python".center(20, "-"))
print("ljust:", "Python".ljust(12, "."))
print("rjust:", "Python".rjust(12, "."))
print("zfill:", "42".zfill(5))
print("format:", "Name: {}, Score: {}".format("Ravi", 88))
